---
- name: Docker up
  hosts: DC
  gather_facts: false

  tasks:
  - name: Deploy project
    include_role:
      name: flask-mongo
    tags:
    - rm-mongo
    - stop-mongo
    - start-mongo
    - backup-mongo
    - restore-mongo
    - rm-flask
    - stop-flask
    - start-flask
