FROM rbakanouski/flask:torch

WORKDIR /workzone

RUN wget {{app_url}} && \
    unzip {{app_url | basename}} && \
    rm {{app_url | basename}} && \
    pip install --no-cache-dir --verbose -r requirements.txt

CMD [ "python3", "run.py" ]
