FROM rbakanouski/flask:torch

WORKDIR /workzone

RUN wget {{app_url}} && \
    unzip {{app_url | basename}} && \
    rm {{app_url | basename}} && \
    pip install --no-cache-dir --verbose -r requirements.txt

CMD [ "/bin/sh", "-c", "python run.py > /var/log/server.log 2>&1" ]
